# Generated by Django 5.0.6 on 2024-05-21 15:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_complaint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
