# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='_complaint_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='_status_at',
            field=models.DateTimeField(null=True),
        ),
    ]
