# Generated by Django 5.0.6 on 2024-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_complaint__complaint_at_complaint__status_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='_status_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='_update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
