# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
